// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv2BNrTm9RUfa5Dy46kOHeVk-PDIrkr8M',
    appId: '1:451165195080:web:fc2ef7a51256edb47c017d',
    messagingSenderId: '451165195080',
    projectId: 'kiddie-ab777',
    authDomain: 'kiddie-ab777.firebaseapp.com',
    storageBucket: 'kiddie-ab777.appspot.com',
    measurementId: 'G-Z3T203TC6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMbay_ioK_O9sdXdRzeSP2_y9RdGgdqOQ',
    appId: '1:451165195080:android:8e42bebcac7a627d7c017d',
    messagingSenderId: '451165195080',
    projectId: 'kiddie-ab777',
    storageBucket: 'kiddie-ab777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj9qTf3It9dcWLXHZcDUaSh947m55e1aM',
    appId: '1:451165195080:ios:5292ef2b48d90cbb7c017d',
    messagingSenderId: '451165195080',
    projectId: 'kiddie-ab777',
    storageBucket: 'kiddie-ab777.appspot.com',
    androidClientId: '451165195080-res3lur9sd5etltue454boul5vg16lq1.apps.googleusercontent.com',
    iosClientId: '451165195080-bbun2b2ergfjtflrm2bq8ol6h3dkg458.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiddie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj9qTf3It9dcWLXHZcDUaSh947m55e1aM',
    appId: '1:451165195080:ios:5292ef2b48d90cbb7c017d',
    messagingSenderId: '451165195080',
    projectId: 'kiddie-ab777',
    storageBucket: 'kiddie-ab777.appspot.com',
    androidClientId: '451165195080-res3lur9sd5etltue454boul5vg16lq1.apps.googleusercontent.com',
    iosClientId: '451165195080-bbun2b2ergfjtflrm2bq8ol6h3dkg458.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiddie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv2BNrTm9RUfa5Dy46kOHeVk-PDIrkr8M',
    appId: '1:451165195080:web:7a2a58a9daf0e2997c017d',
    messagingSenderId: '451165195080',
    projectId: 'kiddie-ab777',
    authDomain: 'kiddie-ab777.firebaseapp.com',
    storageBucket: 'kiddie-ab777.appspot.com',
    measurementId: 'G-7NNYFHEMJK',
  );

}